import type { Audio } from '../types/types'

export const mainAudio: Audio[] = [
  {
    id: 'main001',
    status: true,
    baseSrc: '1st/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
    ],
  },
  {
    id: 'main002',
    status: true,
    baseSrc: '2nd/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004-001.mp3', addtitle: '第1楽章 シャコンヌ' },
      { available: true, data: 3, path: '004-002.mp3', addtitle: '第2楽章 間奏曲' },
      { available: true, data: 3, path: '004-003.mp3', addtitle: '第3楽章 マーチ' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008-001.mp3', addtitle: 'I. ソン・モンテューノ' },
      { available: true, data: 7, path: '008-002.mp3', addtitle: 'II. タンゴ' },
      { available: true, data: 7, path: '008-003.mp3', addtitle: 'III. グワラチャ' },
      { available: true, data: 7, path: '008-004.mp3', addtitle: 'IV. パソ・ドブレ' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
    ],
  },
  {
    id: 'main003',
    status: true,
    baseSrc: '3rd/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005-001.mp3', addtitle: '1. 小序曲' },
      { available: true, data: 4, path: '005-002.mp3', addtitle: '2. 特徴のある踊り a. 小行進曲' },
      { available: true, data: 4, path: '005-003.mp3', addtitle: '2. 特徴のある踊り b. 金米糖の精の踊り' },
      { available: true, data: 4, path: '005-004.mp3', addtitle: '2. 特徴のある踊り c. トレパーク' },
      { available: true, data: 4, path: '005-005.mp3', addtitle: '2. 特徴のある踊り d. アラビアの踊り' },
      { available: true, data: 4, path: '005-006.mp3', addtitle: '2. 特徴のある踊り e. 中国の踊り' },
      { available: true, data: 4, path: '005-007.mp3', addtitle: '2. 特徴のある踊り f. あし笛の踊り' },
      { available: true, data: 4, path: '005-008.mp3', addtitle: '3. 花のワルツ' },
      { available: true, data: 5, path: '006-001.mp3', addtitle: '第1楽章 プレリュードとアズテックダンス' },
      { available: true, data: 5, path: '006-002.mp3', addtitle: '第2楽章 ミサ' },
      { available: true, data: 5, path: '006-003.mp3', addtitle: '第3楽章 カーニバル' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
    ],
  },
  {
    id: 'main004',
    status: true,
    baseSrc: '4th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008-001.mp3', addtitle: 'I. マーチ' },
      { available: true, data: 7, path: '008-002.mp3', addtitle: 'II. ワルツ' },
      { available: true, data: 7, path: '008-003.mp3', addtitle: 'III. ロンド' },
      { available: true, data: 8, path: '009-001.mp3', addtitle: 'I.トッカータ' },
      { available: true, data: 8, path: '009-002.mp3', addtitle: 'II. 間奏曲' },
      { available: true, data: 8, path: '009-003.mp3', addtitle: 'III. 終曲' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3', addtitle: '(部分)' },
    ],
  },
  {
    id: 'main005',
    status: true,
    baseSrc: '5th/5th2/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004-001.mp3' },
      { available: true, data: 4, path: '004-002.mp3' },
      { available: true, data: 5, path: '004-003.mp3' },
      { available: true, data: 6, path: '005.mp3' },
      { available: true, data: 7, path: '006.mp3' },
      { available: true, data: 8, path: '007-001.mp3', addtitle: 'テーマ' },
      { available: true, data: 8, path: '007-002.mp3', addtitle: '盆踊り' },
      { available: true, data: 8, path: '007-003.mp3', addtitle: '朝のうた' },
      { available: true, data: 8, path: '007-004.mp3', addtitle: 'フィナーレ' },
      { available: true, data: 9, path: '008.mp3' },
      { available: true, data: 10, path: '009.mp3' },
      { available: true, data: 11, path: '010.mp3' },
    ],
  },
  {
    id: 'main006',
    status: true,
    baseSrc: '6th/6th2/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008-001.mp3', addtitle: 'I. ファンファーレと序奏' },
      { available: true, data: 7, path: '008-002.mp3', addtitle: 'II. パ・ドゥ・ドゥ' },
      { available: true, data: 7, path: '008-003.mp3', addtitle: 'III. 風変わりなポルカ' },
      { available: true, data: 7, path: '008-004.mp3', addtitle: 'IV. 全員の踊り' },
      { available: true, data: 8, path: '009-001.mp3', addtitle: 'I. パストラール' },
      { available: true, data: 8, path: '009-002.mp3', addtitle: 'II. 間奏曲' },
      { available: true, data: 8, path: '009-003.mp3', addtitle: 'III. メヌエット' },
      { available: true, data: 8, path: '009-004.mp3', addtitle: 'IV. ファランドール' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3' },
    ],
  },
  {
    id: 'main007',
    status: true,
    baseSrc: '7th/7th2/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003-001.mp3', addtitle: '第1楽章' },
      { available: true, data: 2, path: '003-002.mp3', addtitle: '第2楽章' },
      { available: true, data: 2, path: '003-003.mp3', addtitle: '第3楽章' },
      { available: true, data: 2, path: '003-004.mp3', addtitle: '第4楽章' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008-001.mp3', addtitle: '第1楽章 祈り' },
      { available: true, data: 7, path: '008-002.mp3', addtitle: '第2楽章 唄' },
      { available: true, data: 7, path: '008-003.mp3', addtitle: '第3楽章 祭り' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
    ],
  },
  {
    id: 'main008',
    status: true,
    baseSrc: '8th/8th2/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004-001.mp3', addtitle: '第1楽章 高原にて' },
      { available: true, data: 3, path: '004-002.mp3', addtitle: '第2楽章 ブラッドフォードのバラード' },
      { available: true, data: 3, path: '004-003.mp3', addtitle: '第3楽章 ダーウェントウォーターにて' },
      { available: true, data: 4, path: '005-001.mp3' },
      { available: true, data: 4, path: '005-002.mp3' },
      { available: true, data: 4, path: '005-003.mp3' },
      { available: true, data: 5, path: '006-001.mp3', addtitle: '第1部 ボルゲーゼ荘の松' },
      { available: true, data: 5, path: '006-002.mp3', addtitle: '第2部 カタコンバ付近の松' },
      { available: true, data: 5, path: '006-003.mp3', addtitle: '第3部 ジャニコロの松' },
      { available: true, data: 5, path: '006-004.mp3', addtitle: '第4部 アッピア街道の松' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
    ],
  },
  {
    id: 'main009',
    status: true,
    baseSrc: '9th/9th2/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003-001.mp3', addtitle: 'I. リスボン' },
      { available: true, data: 2, path: '003-002.mp3', addtitle: 'II. ホークストウの農場' },
      { available: true, data: 2, path: '003-003.mp3', addtitle: 'III. ラフォード公園の密猟者' },
      { available: true, data: 2, path: '003-004.mp3', addtitle: 'IV. 元気な若い水夫' },
      { available: true, data: 2, path: '003-005.mp3', addtitle: 'V. メルボルン卿' },
      { available: true, data: 2, path: '003-006.mp3', addtitle: 'VI. 行方不明の婦人が見つかった' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005-001.mp3' },
      { available: true, data: 4, path: '005-002.mp3' },
      { available: true, data: 4, path: '005-003.mp3' },
      { available: true, data: 4, path: '005-004.mp3' },
      { available: true, data: 4, path: '005-005.mp3' },
      { available: true, data: 4, path: '005-006.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
    ],
  },
  {
    id: 'main010',
    status: true,
    baseSrc: '10th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003-001.mp3', addtitle: '1. カウボーイの休日' },
      { available: true, data: 2, path: '003-002.mp3', addtitle: '2. 畜舎の夜想曲' },
      { available: true, data: 2, path: '003-003.mp3', addtitle: '3. 土曜の夜のワルツ' },
      { available: true, data: 2, path: '003-004.mp3', addtitle: '4. ホーダウン' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006-001.mp3', addtitle: '1. 小舟にて' },
      { available: true, data: 5, path: '006-002.mp3', addtitle: '2. 行列' },
      { available: true, data: 5, path: '006-003.mp3', addtitle: '3. メヌエット' },
      { available: true, data: 5, path: '006-004.mp3', addtitle: '4. バレエ' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
    ],
  },
  {
    id: 'main011',
    status: true,
    baseSrc: '11th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3', addtitle: '1. ヌピア人の踊り' },
      { available: true, data: 2, path: '004.mp3', addtitle: '2. ヌピア人の奴隷の踊り' },
      { available: true, data: 2, path: '005.mp3', addtitle: '3. トロイの娘たちの踊り' },
      { available: true, data: 2, path: '006.mp3', addtitle: '4. フリネの踊り' },
      { available: true, data: 3, path: '007.mp3' },
      { available: true, data: 4, path: '008.mp3', addtitle: '第1曲 プレリュード、アンティフォナル・コールI' },
      { available: true, data: 4, path: '009.mp3', addtitle: '第2曲 ソング・アンド・ダンス' },
      { available: true, data: 4, path: '010.mp3', addtitle: '第3曲 ポストリュードアンティフォナル・コールII' },
      { available: true, data: 5, path: '011.mp3', addtitle: '第1楽章' },
      { available: true, data: 5, path: '012.mp3', addtitle: '第2楽章' },
      { available: true, data: 6, path: '013.mp3' },
      { available: true, data: 7, path: '014.mp3' },
      { available: true, data: 8, path: '015.mp3' },
      { available: true, data: 9, path: '016.mp3' },
    ],
  },
  {
    id: 'main012',
    status: true,
    baseSrc: '12th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3', addtitle: '' },
      { available: true, data: 4, path: '006.mp3', addtitle: '' },
      { available: true, data: 4, path: '007.mp3', addtitle: '' },
      { available: true, data: 4, path: '008.mp3', addtitle: '' },
      { available: true, data: 4, path: '009.mp3', addtitle: '' },
      { available: true, data: 4, path: '010.mp3', addtitle: '' },
      { available: true, data: 4, path: '011.mp3', addtitle: '' },
      { available: true, data: 4, path: '012.mp3', addtitle: '' },
      { available: true, data: 4, path: '013.mp3', addtitle: '' },
      { available: true, data: 4, path: '014.mp3', addtitle: '' },
      { available: true, data: 5, path: '015.mp3' },
      { available: true, data: 6, path: '016.mp3' },
    ],
  },
  {
    id: 'main013',
    status: true,
    baseSrc: '13th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3', addtitle: '1. この世は限りなく最良のもの' },
      { available: true, data: 1, path: '003.mp3', addtitle: '2. ウェストファリア・コラールと戦いの場面' },
      { available: true, data: 1, path: '004.mp3', addtitle: '3. 判決' },
      { available: true, data: 1, path: '005.mp3', addtitle: '4. きらびやかに楽しく' },
      { available: true, data: 1, path: '006.mp3', addtitle: '5. 我らの庭を耕そう' },
      { available: true, data: 2, path: '007.mp3' },
      { available: true, data: 3, path: '008.mp3' },
      { available: true, data: 4, path: '009.mp3' },
      { available: true, data: 5, path: '010.mp3' },
      { available: true, data: 6, path: '011.mp3', addtitle: 'No.5 Bellicoso' },
      { available: true, data: 6, path: '012.mp3', addtitle: 'No.6 Amoroso' },
      { available: true, data: 6, path: '013.mp3', addtitle: 'No.11 Risoluto' },
      { available: true, data: 7, path: '014.mp3' },
      { available: true, data: 8, path: '015.mp3', addtitle: '1. 隣人の踊り' },
      { available: true, data: 8, path: '016.mp3', addtitle: '2. 粉屋の踊り' },
      { available: true, data: 8, path: '017.mp3', addtitle: '3. 終幕の踊り' },
      { available: true, data: 9, path: '018.mp3' },
      { available: true, data: 10, path: '019.mp3' },
    ],
  },
  {
    id: 'main014',
    status: true,
    baseSrc: '14th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3', addtitle: '第1楽章' },
      { available: true, data: 1, path: '003.mp3', addtitle: '第2楽章' },
      { available: true, data: 1, path: '004.mp3', addtitle: '第3楽章' },
      { available: true, data: 2, path: '005.mp3', addtitle: '1. 幻想曲(ひえつき節による)' },
      { available: true, data: 2, path: '006.mp3', addtitle: '2. 奇想曲(佐賀の田植唄による)' },
      { available: true, data: 2, path: '007.mp3', addtitle: '3. 哀歌(福連木の子守唄による)' },
      { available: true, data: 2, path: '008.mp3', addtitle: '4. 頌歌(筑後酒造唄による)' },
      { available: true, data: 3, path: '009.mp3' },
      { available: true, data: 4, path: '010.mp3' },
      { available: true, data: 5, path: '011.mp3' },
    ],
  },
  {
    id: 'main015',
    status: true,
    baseSrc: '15th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3', addtitle: 'I. ファンファーレと式典行進' },
      { available: true, data: 5, path: '007.mp3', addtitle: 'II. 草の道' },
      { available: true, data: 5, path: '008.mp3', addtitle: 'III. 収穫祭' },
      { available: true, data: 6, path: '009.mp3' },
      { available: true, data: 7, path: '010.mp3', addtitle: 'I. 前奏曲「ヴェニス」' },
      { available: true, data: 7, path: '011.mp3', addtitle: 'II. 朝の音楽「キプロス」' },
      { available: true, data: 7, path: '012.mp3', addtitle: 'III. オセロとデスデモナ' },
      { available: true, data: 7, path: '013.mp3', addtitle: 'IV. 廷臣たちの入場' },
      { available: true, data: 7, path: '014.mp3', addtitle: 'V. デスデモナの死、終曲' },
      { available: true, data: 8, path: '015.mp3' },
      { available: true, data: 9, path: '016.mp3' },
    ],
  },
  {
    id: 'main016',
    status: true,
    baseSrc: '16th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3', addtitle: 'I. リリパット' },
      { available: true, data: 2, path: '004.mp3', addtitle: 'II. ブロブディングナグ' },
      { available: true, data: 2, path: '005.mp3', addtitle: 'III. ラピュータ' },
      { available: true, data: 2, path: '006.mp3', addtitle: 'IV. フィヌム' },
      { available: true, data: 3, path: '007.mp3' },
      { available: true, data: 4, path: '008.mp3' },
      { available: true, data: 5, path: '009.mp3' },
      { available: true, data: 6, path: '010.mp3' },
      { available: true, data: 7, path: '011.mp3' },
      { available: true, data: 8, path: '012.mp3' },
      { available: true, data: 9, path: '013.mp3' },
      { available: true, data: 10, path: '014.mp3' },
    ],
  },
  {
    id: 'main017',
    status: true,
    baseSrc: '17th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3', addtitle: 'I. 行進曲「日曜日で17歳」' },
      { available: true, data: 2, path: '004.mp3', addtitle: 'II. 間奏曲「マイ・ポニー・ボーイ」' },
      { available: true, data: 2, path: '005.mp3', addtitle: 'III. 行進曲「サマーセットの民謡」' },
      { available: true, data: 3, path: '006.mp3' },
      { available: true, data: 4, path: '007.mp3' },
      { available: true, data: 5, path: '008.mp3' },
      { available: true, data: 6, path: '009.mp3' },
      { available: true, data: 7, path: '010.mp3' },
      { available: true, data: 8, path: '011.mp3' },
      { available: true, data: 9, path: '012.mp3' },
      { available: true, data: 10, path: '013.mp3' },
      { available: true, data: 11, path: '014.mp3' },
      { available: true, data: 12, path: '015.mp3' },
    ],
  },
  {
    id: 'main018',
    status: true,
    baseSrc: '18th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3', addtitle: 'I. プロローグ' },
      { available: true, data: 6, path: '008.mp3', addtitle: 'II. 道化師のギャロップ' },
      { available: true, data: 6, path: '009.mp3', addtitle: 'V. パントマイム' },
      { available: true, data: 6, path: '010.mp3', addtitle: 'VII. 小さな抒情的シーン' },
      { available: true, data: 6, path: '011.mp3', addtitle: 'X. エピローグ' },
      { available: true, data: 7, path: '012.mp3' },
      { available: true, data: 8, path: '013.mp3' },
      { available: true, data: 9, path: '014.mp3' },
      { available: true, data: 10, path: '015.mp3' },
      { available: true, data: 11, path: '016.mp3' },
      { available: true, data: 12, path: '017.mp3' },
      { available: true, data: 13, path: '018.mp3' },
      { available: true, data: 14, path: '019.mp3' },
      { available: true, data: 15, path: '020.mp3' },
    ],
  },
  {
    id: 'main019',
    status: true,
    baseSrc: '19th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3' },
      { available: true, data: 12, path: '013.mp3' },
      { available: true, data: 13, path: '014.mp3' },
      { available: true, data: 14, path: '015.mp3' },
    ],
  },
  {
    id: 'main020',
    status: true,
    baseSrc: '20th/',
    data: [
      { available: true, data: 0, path: '014.mp3' },
      { available: true, data: 1, path: '015.mp3' },
      { available: true, data: 2, path: '016.mp3' },
      { available: true, data: 3, path: '018.mp3' },
      { available: true, data: 4, path: '019.mp3' },
      { available: true, data: 5, path: '001.mp3' },
      { available: true, data: 6, path: '002.mp3' },
      { available: true, data: 7, path: '003.mp3' },
      { available: true, data: 8, path: '004.mp3' },
      { available: true, data: 9, path: '005.mp3' },
      { available: true, data: 10, path: '006.mp3' },
      { available: true, data: 11, path: '007.mp3' },
      { available: true, data: 12, path: '008.mp3' },
      { available: true, data: 13, path: '009.mp3' },
      { available: true, data: 14, path: '010.mp3' },
      { available: true, data: 15, path: '011.mp3' },
      { available: true, data: 16, path: '012.mp3' },
      { available: true, data: 17, path: '013.mp3' },
    ],
  },
  {
    id: 'main021',
    status: true,
    baseSrc: '21st/',
    data: [
      { available: true, data: 0, path: '010.mp3' },
      { available: true, data: 1, path: '011.mp3' },
      { available: true, data: 2, path: '012.mp3' },
      { available: true, data: 3, path: '013.mp3' },
      { available: true, data: 4, path: '001.mp3' },
      { available: true, data: 5, path: '002.mp3' },
      { available: true, data: 6, path: '003.mp3' },
      { available: true, data: 7, path: '004.mp3' },
      { available: true, data: 8, path: '005.mp3' },
      { available: true, data: 9, path: '006.mp3' },
      { available: true, data: 10, path: '007.mp3' },
      { available: true, data: 11, path: '008.mp3' },
      { available: true, data: 12, path: '009.mp3' },
    ],
  },
  {
    id: 'main022',
    status: true,
    baseSrc: '22nd/',
    data: [
      { available: true, data: 0, path: '008.mp3' },
      { available: true, data: 1, path: '009.mp3' },
      { available: true, data: 2, path: '010.mp3' },
      { available: true, data: 3, path: '001.mp3' },
      { available: true, data: 4, path: '002.mp3' },
      { available: true, data: 5, path: '003.mp3' },
      { available: true, data: 6, path: '004.mp3' },
      { available: true, data: 7, path: '005.mp3' },
      { available: true, data: 8, path: '006.mp3' },
      { available: true, data: 9, path: '007.mp3' },
    ],
  },
  {
    id: 'main023',
    status: true,
    baseSrc: '23rd/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
    ],
  },
  {
    id: 'main024',
    status: true,
    baseSrc: '24th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
    ],
  },
  {
    id: 'main025',
    status: true,
    baseSrc: '25th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
    ],
  },
  {
    id: 'main026',
    status: true,
    baseSrc: '26th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3', addtitle: 'シェルター島' },
      { available: true, data: 4, path: '006.mp3', addtitle: 'キャッツキル山地' },
      { available: true, data: 4, path: '007.mp3', addtitle: 'ニューヨーク' },
      { available: true, data: 5, path: '008.mp3' },
      { available: true, data: 6, path: '009.mp3' },
      { available: true, data: 7, path: '010.mp3' },
    ],
  },
  {
    id: 'main027',
    status: true,
    baseSrc: '27th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 6, path: '008.mp3' },
      { available: true, data: 6, path: '009.mp3' },
      { available: true, data: 6, path: '010.mp3' },
      { available: true, data: 7, path: '011.mp3' },
      { available: true, data: 8, path: '012.mp3' },
      { available: true, data: 9, path: '013.mp3' },
    ],
  },
  {
    id: 'main028',
    status: true,
    baseSrc: '28th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
    ],
  },
  {
    id: 'main029',
    status: true,
    baseSrc: '29th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3', addtitle: '第1楽章 シャコンヌ' },
      { available: true, data: 8, path: '010.mp3', addtitle: '第2楽章 間奏曲' },
      { available: true, data: 8, path: '011.mp3', addtitle: '第3楽章 マーチ' },
      { available: true, data: 9, path: '012.mp3' },
      { available: true, data: 10, path: '013.mp3' },
      { available: true, data: 11, path: '014.mp3' },
      { available: true, data: 12, path: '015.mp3' },
    ],
  },
  {
    id: 'main030',
    status: true,
    baseSrc: '30th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
    ],
  },
  {
    id: 'main031',
    status: true,
    baseSrc: '31st/',
    data: [
      { available: true, data: 0, path: '001-001.mp3', addtitle: '1. Charanga di Xiomara Reyes' },
      { available: true, data: 0, path: '001-002.mp3', addtitle: '2. Merengue Sempre di Aychem Sunal' },
      { available: true, data: 0, path: '001-003.mp3', addtitle: '3. Dansa Latino di Maria del Real' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007-001.mp3', addtitle: '第1楽章 プレリュードとアズテック・ダンス' },
      { available: true, data: 6, path: '007-002.mp3', addtitle: '第2楽章 ミサ' },
      { available: true, data: 6, path: '007-003.mp3', addtitle: '第3楽章 カーニヴァル' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
    ],
  },
  {
    id: 'main033',
    status: true,
    baseSrc: '33rd/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003-001.mp3', addtitle: '作品46 第2番' },
      { available: true, data: 2, path: '003-002.mp3', addtitle: '作品72 第2番' },
      { available: true, data: 2, path: '003-003.mp3', addtitle: '作品46 第8番' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
    ],
  },
  {
    id: 'main034',
    status: true,
    baseSrc: '34th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
    ],
  },
  {
    id: 'main035',
    status: true,
    baseSrc: '35th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
    ],
  },
  {
    id: 'main037',
    status: true,
    baseSrc: '37th/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3', addtitle: '第1楽章' },
      { available: true, data: 2, path: '004.mp3', addtitle: '第2楽章' },
      { available: true, data: 2, path: '005.mp3', addtitle: '第3楽章' },
      { available: true, data: 2, path: '006.mp3', addtitle: '第4楽章' },
      { available: true, data: 3, path: '007.mp3' },
      { available: true, data: 4, path: '008.mp3', addtitle: '第4楽章「断頭台への行進」' },
      { available: true, data: 4, path: '009.mp3', addtitle: '第5楽章「魔女の夜宴の夢」' },
      { available: true, data: 5, path: '010.mp3' },
      { available: true, data: 6, path: '011.mp3' },
    ],
  },
]
