const miniConcert = [
  {
    id: 'mini2007',
    status: true,
    baseSrc: 'mini2007/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
    ],
  },
  {
    id: 'mini2008',
    status: true,
    baseSrc: 'mini2008/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
    ],
  },
  {
    id: 'mini2009',
    status: true,
    baseSrc: 'mini2009/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3' },
    ],
  },
  {
    id: 'mini2010',
    status: true,
    baseSrc: 'mini2010/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
    ],
  },
  {
    id: 'mini2011',
    status: true,
    baseSrc: 'mini2011/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3' },
      { available: true, data: 12, path: '013.mp3' },
      { available: true, data: 13, path: '014.mp3' },
      { available: true, data: 14, path: '015.mp3' },
    ],
  },
  {
    id: 'mini2012',
    status: true,
    baseSrc: 'mini2012/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3' },
    ],
  },
  {
    id: 'mini2013',
    status: true,
    baseSrc: 'mini2013/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3' },
    ],
  },
  {
    id: 'mini2014',
    status: true,
    baseSrc: 'mini2014/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3' },
      { available: true, data: 12, path: '013.mp3' },
    ],
  },
  {
    id: 'mini2015',
    status: true,
    baseSrc: 'mini2015/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
      { available: true, data: 11, path: '012.mp3' },
    ],
  },
  {
    id: 'mini2016',
    status: true,
    baseSrc: 'mini2016/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
    ],
  },
  {
    id: 'mini2017',
    status: true,
    baseSrc: 'mini2017/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
    ],
  },
  {
    id: 'mini2018',
    status: true,
    baseSrc: 'mini2018/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
    ],
  },
  {
    id: 'mini2019',
    status: true,
    baseSrc: 'mini2019/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
      { available: true, data: 10, path: '011.mp3' },
    ],
  },
  {
    id: 'mini2021',
    status: true,
    baseSrc: 'mini2021/',
    data: [
      { available: true, data: 0, path: '001.mp3' },
      { available: true, data: 1, path: '002.mp3' },
      { available: true, data: 2, path: '003.mp3' },
      { available: true, data: 3, path: '004.mp3' },
      { available: true, data: 4, path: '005.mp3' },
      { available: true, data: 5, path: '006.mp3' },
      { available: true, data: 6, path: '007.mp3' },
      { available: true, data: 7, path: '008.mp3' },
      { available: true, data: 8, path: '009.mp3' },
      { available: true, data: 9, path: '010.mp3' },
    ],
  },
]

module.exports = {
  miniConcert,
}
